cluster:
  name: ${CLUSTER_NAME}

node:
  master: ${NODE_MASTER}
  data: ${NODE_DATA}
  name: ${NODE_NAME}
  ingest: ${NODE_INGEST}
  max_local_storage_nodes: ${MAX_LOCAL_STORAGE_NODES}

network.host: ${NETWORK_HOST}

path:
  data: /data/data
  logs: /data/log

bootstrap:
  memory_lock: true

http:
  enabled: ${HTTP_ENABLE}
  compression: true
  cors:
    enabled: ${HTTP_CORS_ENABLE}
    allow-origin: ${HTTP_CORS_ALLOW_ORIGIN}

discovery:
  zen:
    ping.unicast.hosts: ${DISCOVERY_SERVICE}
    minimum_master_nodes: ${NUMBER_OF_MASTERS}

action.auto_create_index: .security,.monitoring*,.watches,.triggered_watches,.watcher-history*,logstash-*

xpack:
  # Set to false to disable X-Pack security. Configure in both elasticsearch.yml and kibana.yml.
  security.enabled: ${X_PACK_SECURITY_ENABLED}
  # Set to false to disable X-Pack monitoring. Configure in both elasticsearch.yml and kibana.yml.
  monitoring.enabled: ${X_PACK_MONITORING_ENABLED}
  # Set to false to disable X-Pack graph. Configure in both elasticsearch.yml and kibana.yml.
  graph.enabled: ${X_PACK_GRAPH_ENABLED}
  # Set to false to disable Watcher. Configure in elasticsearch.yml only.
  watcher.enabled: ${X_PACK_WATCHER_ENABLED}





